BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[TBL_CORE_USERS] (
    [id] INT NOT NULL IDENTITY(1,1),
    [firstName] VARCHAR(30) NOT NULL,
    [lastName] VARCHAR(30) NOT NULL,
    [msisdn] VARCHAR(9) NOT NULL,
    [username] VARCHAR(50) NOT NULL,
    [password] VARCHAR(60) NOT NULL,
    [active] INT NOT NULL CONSTRAINT [TBL_CORE_USERS_active_df] DEFAULT 1,
    [refreshToken] NVARCHAR(1000),
    [roleId] INT NOT NULL CONSTRAINT [TBL_CORE_USERS_roleId_df] DEFAULT 1,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [TBL_CORE_USERS_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2,
    CONSTRAINT [TBL_CORE_USERS_pkey] PRIMARY KEY ([id]),
    CONSTRAINT [TBL_CORE_USERS_msisdn_key] UNIQUE ([msisdn]),
    CONSTRAINT [TBL_CORE_USERS_username_key] UNIQUE ([username])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_CORE_ROLES] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] VARCHAR(30) NOT NULL,
    CONSTRAINT [TBL_CORE_ROLES_pkey] PRIMARY KEY ([id]),
    CONSTRAINT [TBL_CORE_ROLES_name_key] UNIQUE ([name])
);

-- CreateIndex
CREATE INDEX [TBL_CORE_USERS_username_idx] ON [dbo].[TBL_CORE_USERS]([username]);

-- AddForeignKey
ALTER TABLE [dbo].[TBL_CORE_USERS] ADD CONSTRAINT [TBL_CORE_USERS_roleId_fkey] FOREIGN KEY ([roleId]) REFERENCES [dbo].[TBL_CORE_ROLES]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
